name: Merge Machine CI/CD Action Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep to MergeMachine RG
      env:
        WEBAPP_NAME: mergemachinep
      run: |
        # Publish application to a folder
        dotnet publish --configuration Release --output publish

        # Create a zip package of the published output
        sudo apt-get update -y
        sudo apt-get install -y zip
        cd publish
        zip -r ../publish.zip .
        cd ..

        # Deploy infrastructure (Bicep) and create/update the Web App
        az deployment group create \
          --resource-group MergeMachine \
          --template-file infra/MergeMachine.bicep \

        # Zip-deploy the published app to the created web app
        az webapp deployment source config-zip \
          --resource-group MergeMachine \
          --name mergemachinep \
          --src publish.zip
